{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf600
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red58\green62\blue68;\red237\green236\blue236;}
{\*\expandedcolortbl;\csgray\c100000;\cssrgb\c29412\c30980\c33725;\cssrgb\c94510\c94118\c94118;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
COMPILER = gcc\
CFLAGS = -Wall \
\
all: formula \
\
formula: \
	gcc -Wall -g -o formula formula.c nCr.s  \
\
clean: \
	rm -f formula \
	rm -f *.o}